export const APP_CONSTANTS = {
  MIN_SEATS_PER_SESSION: 16,
  DEFAULT_RESERVATION_TTL_SECONDS: 30,
  REDLOCK_TTL_MS: 5000,
  REDLOCK_RETRY_COUNT: 3,
  REDLOCK_RETRY_DELAY_MS: 200,
  REDLOCK_RETRY_JITTER_MS: 100,
} as const;
